### ISSUE TITLE
percentages are blowing  up

### ISSUE THREAD

**Issue by ballPointPenguin** [metasoarous/2020-election-battleground-viz#1]
There's a handful of percentages that are now being displayed in the 10,000x range. Maybe it is simply an order of magnitude.

**Comment by metasoarous** [comment]
Thanks for the catch @ballPointPenguin. I saw this last night. Turns out they've started throwing some funky stuff in the upstream CSVs, and my naive parsing routine was failing to catch it. Switched to a proper library for this, and all should be well now.

Worth noting though that at least some of these values are intentional (recent Georgia hurdles in particular), since there aren't enough votes left for Trump to possibly win (huzzah!). So adding an `(impossible)` annotation to make clear that these numbers are correct.

Thanks again for the catch! Changes should now be live if you reload!
